apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG:-digital-twin}
      defaultBucket: ${INFLUXDB_BUCKET:-room_sensors}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true
